name: "CNC_Plotter_ESP32"
board: "ESP32 Dev Module"
stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0
axes:
  shared_stepper_disable_pin: gpio.13:low
  x:
    steps_per_mm: 320.0
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 300
    homing:
      cycle: 1
      mpos_mm: 0
      feed_mm_per_min: 500
      seek_mm_per_min: 1000
      dwell_ms: 100
      pullback_mm: 5
    motor0:
      direction_pin: gpio.16:low
      step_pin: gpio.17
  y:
    steps_per_mm: 106.667
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 100
    max_travel_mm: 300
    homing:
      cycle: 1
      mpos_mm: 0
      feed_mm_per_min: 500
      seek_mm_per_min: 1000
      dwell_ms: 100
      pullback_mm: 5
    motor0:
      direction_pin: gpio.18:low
      step_pin: gpio.19
limits:
  x_min_pin: gpio.34:high:pu
  x_max_pin: gpio.36:high:pu
  y_min_pin: gpio.35:high:pu
  y_max_pin: gpio.39:high:pu
  z_min_pin: gpio.32:high:pu
  z_probe_dwell_ms: 50
servo:
  pin: gpio.2
  rate_hz: 50
  max_pulse_us: 2000
  min_pulse_us: 1000
  startup_delay_ms: 500
  commands:
    - command: M3 S0
      value: 1500
    - command: M3 S1
      value: 1000
probe:
  pin: gpio.32:high:pu
wifi:
  ssid: '**********'
  password: '**********'
  hostname: plotter_fluidnc
  mode: STA
control:
  feed_hold_pin: gpio.25:high:pu
  estop_pin: gpio.26:high:pu
startup_lines:
  - G21
  - G90
  - G92 X0 Y0 Z0